### ISSUE TITLE
修改意见

### ISSUE THREAD

**Issue by zpp1314** [1147529365/Today-Campus#2]
大佬
![Screenshot_20240430_010021.jpg](https://github.com/1147529365/Today-Campus/assets/93334436/8aeded8a-0291-432b-803f-29f08c634181)

这里的抄送人下面目的地，填了之后没有目的地三个字在前面，需要加一个(目的地：)，还有上面的销假规则是：离校、非离校请假需要销假

**Comment by zpp1314** [comment]
![mmexport1714410296752.jpg](https://github.com/1147529365/Today-Campus/assets/93334436/a6116e29-1d95-4934-97c4-d10b40b9ea61)

这个是现在最新版本的今日校园的界面🙏🏻🙏🏻🙏🏻

**Comment by zpp1314** [comment]
![IMG_20240430_010845.jpg](https://github.com/1147529365/Today-Campus/assets/93334436/a48d49d7-9754-4960-92e1-b71ecbc13fc7)



这个是现在最新版本的今日校园的界面🙏🏻🙏🏻🙏🏻

**Comment by 1147529365** [comment]
> 大佬
> ![Screenshot_20240430_010021.jpg](https://github.com/1147529365/Today-Campus/assets/93334436/8aeded8a-0291-432b-803f-29f08c634181)
> 
> 这里的抄送人下面目的地，填了之后没有目的地三个字在前面，需要加一个(目的地：)，还有上面的销假规则是：离校、非离校请假需要销假
> 
> 
> 

这个目的地还没有开发完，临时更新不小心同步到你那里了，我先把旧版给你推送过去

**Comment by 1147529365** [comment]
> ![IMG_20240430_010845.jpg](https://github.com/1147529365/Today-Campus/assets/93334436/a48d49d7-9754-4960-92e1-b71ecbc13fc7)
> 
> 
> 
> 这个是现在最新版本的今日校园的界面🙏🏻🙏🏻🙏🏻

留一下你的QQ号

**Comment by zpp1314** [comment]
1976712810

**Comment by zpp1314** [comment]
> > 大佬
> > ![Screenshot_20240430_010021.jpg](https://github.com/1147529365/Today-Campus/assets/93334436/8aeded8a-0291-432b-803f-29f08c634181)
> > 
> > 这里的抄送人下面目的地，填了之后没有目的地三个字在前面，需要加一个(目的地：)，还有上面的销假规则是：离校、非离校请假需要销假
> > 
> > 
> > 
> 
> 这个目的地还没有开发完，临时更新不小心同步到你那里了，我先把旧版给你推送过去

好的😄

**Comment by gjhcghh** [comment]
大佬，我也想要一份旧版

**Comment by zpp1314** [comment]
> 大佬，我也想要一份旧版

旧版本可以直接下载呀

**Comment by gjhcghh** [comment]
在哪下，给个地址呗，我没找到

**Comment by 1147529365** [comment]
> 
> 在哪下，给个地址呗，我没找到

直接在release下载就的就是旧版
